export const CURRENCY_DATA = 'CURRENCY_DATA'
export const CURRENCY_DATA_SUCCESS = 'CURRENCY_DATA_SUCCESS'
export const CURRENCY_DATA_FAIL = 'CURRENCY_DATA_FAIL'

export const EXCHANGE_DATA = 'EXCHANGE_DATA'
export const EXCHANGE_DATA_SUCCESS = 'EXCHANGE_DATA_SUCCESS'
export const EXCHANGE_DATA_FAIL = 'EXCHANGE_DATA_FAIL'

export const HISTORIC_EXCHANGE = 'HISTORIC_EXCHANGE'
export const HISTORIC_EXCHANGE_SUCCESS = 'HISTORIC_EXCHANGE_SUCCESS'
export const HISTORIC_EXCHANGE_FAIL = 'HISTORIC_EXCHANGE_FAIL'